services:
  microservice:
    build: ./JobPosts/
    ports:
      - "8080:8080"
    links:
      - "database:jobsdb"
    depends_on:
      - database

  database:
    build: ./PostgresDB/
    ports:
      - "5432:5432"